### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by michj3** [DianaShen1224/Donaldson-Paper#1]
Opening statement summary

I am peer reviewing Diana's paper on Toronto's shelter system. 

Strong positive points

The paper has a very in-depth analysis and discussion about the shelter system, which was very easy to understand coming from someone who does not have prior knowledge on this subject. It was well-written and an interesting piece. Good job! I like how you tied in a lot of greater context for the issues you were discussing. 

Critical improvements needed

There aren't too many critical improvements needed, although I think if you added a short conclusion at the end, it would tie the paper together nicely!

Please consider adding/changing/removing:

- I like how in depth and detailed the abstract is, but perhaps be a bit more general in your most significant finding in the abstract and leave the percentages/specific findings for the data and results section. It feels like you're giving away too much in the abstract right now. 
- a few grammar and small changes: i would fully write out the months in the introduction. It feels a bit informal to use the abbreviations. 
- A few formatting issues: there are some extra spaces between characters that you should pay attention to
- Just a small organizational thing: maybe put the figure you are referencing in the data section closer to the paragraph you are talking about them, so it's easier for the readers to picture what you are talking about while it is happening. It feels like I need to scroll back and forth, which just decreases user experience a bit. 

Evaluation: 
- 1 point for R being appropriately cited
- 1 point for LLMs being appropriately documented
- 1 mark for title: could be more clear, uses a lot of technical terms that without context, may be confusing
- 2 points for author, date, and repo being on the paper
- 3 points for abstract: see above for comments
- 10 points for data: very clear, variables were clearly explained
- 2 points for measurement: while it is mentioned, it could be more in depth
- 4 points for prose: see above comments
- 1 point for cross references done correctly
- 2 points for caption: very clear and detailed
- 4 points for reference: all done very clearly and correctly
- 2 points for commits: the commits that are visible have clear messages on why each was made
- 2 points for sketches: gives readers a good understanding of general thought process
- 2.5 points for tests: i think you can comment more to guide the readers through the coding process

Reason:

overall, well done! Just a few remarks and comments but the paper is clear and concise and interesting to read!

**Comment by DianaShen1224** [comment]
Thank you so much for your review! I have updated a summary /conclusion of the paper in the discussion part. Improving the abstract to make it more clear and short. Adding a literature review for the measurement for in-depth. And add comments in the test scripts to guide the readers. Also, improving the formatting and grammar issues of the paper.
